export const SCENE_KEYS = {
    PRELOAD_SCENE: 'PRELOAD_SCENE',
    GAME_SCENE: 'GAME_SCENE',
    GAME_TEST_SCENE: 'GAME_TEST_SCENE',
    UI_SCENE: 'UI_SCENE',
    GAME_OVER_SCENE: 'GAME_OVER_SCENE',
    START_SCREEN: 'START_SCREEN',
    PAUSE_MENU: 'PAUSE_MENU',
    CONGRATULATIONS: 'CONGRATULATIONS',
    LEADERBOARD_SCENE: 'LEADERBOARD_SCENE',
} as const;
